### ISSUE TITLE
npm install fails because of malformed JSON

### ISSUE THREAD

**Issue by pianomister** [IBM/type#118]
I tried to install this package via `npm install @ibm/type` today, but it fails because of a malformed JSON returned by the npm registry. Seems there is a HTML doctype defined in the file.

**Comment by seejamescode** [comment]
Hi @pianomister, I just had a successful install to test. Can you share the logs of the installation as well as your `npm` and `node` version numbers?

**Comment by pianomister** [comment]
Hi @seejamescode,
npm tries to fetch https://npm-registry.whitewater.ibm.com/@ibm%2ftype, which returns a note that the Whitewater npm pilot is no more. Here is a cat of the error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/user/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/Users/user/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@ibm/type',
1 verbose cli   '--save-dev' ]
2 info using npm@5.5.1
3 info using node@v8.6.0
4 verbose npm-session f52d42a627cf5dd1
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://npm-registry.whitewater.ibm.com/@ibm%2ftype 1502ms
8 silly fetchPackageMetaData error for @ibm/type@latest Unexpected token < in JSON at position 0 while parsing near '<!DOCTYPE html>
8 silly fetchPackageMetaData <htm...'
9 verbose stack SyntaxError: Unexpected token < in JSON at position 0 while parsing near '<!DOCTYPE html>
9 verbose stack <htm...'
9 verbose stack     at JSON.parse (<anonymous>)
9 verbose stack     at parseJson (/Users/user/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
9 verbose stack     at consumeBody.call.then.buffer (/Users/user/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
9 verbose stack     at <anonymous>
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
10 verbose cwd /Users/user/git/my-repo
11 verbose Darwin 17.2.0
12 verbose argv "/Users/user/.nvm/versions/node/v8.6.0/bin/node" "/Users/user/.nvm/versions/node/v8.6.0/bin/npm" "i" "@ibm/type" "--save-dev"
13 verbose node v8.6.0
14 verbose npm  v5.5.1
15 error Unexpected token < in JSON at position 0 while parsing near '<!DOCTYPE html>
15 error <htm...'
16 verbose exit [ 1, true ]
```

**Comment by seejamescode** [comment]
Ah, I see the problem @pianomister. IBM’s NPM Enterprise registry was shut down at the new year. Remove anything that tells your project to use that registry. `@ibm/type` is actually published on the public NPM registry.

**Comment by dessty** [comment]
I'm trying to reopen this tickets as I have a similar issue. I created another ticket. Please see: https://github.com/IBM/plex/issues/226
